extends RefCounted
class_name ShipAILimboKeys

const VAR_TARGET := &"ship_target"
const VAR_INTENT := &"ship_intent"
const VAR_TARGET_DISTANCE := &"ship_target_distance"
const VAR_PRESSURE_PHASE := &"ship_pressure_phase"
const VAR_PRESSURE := &"ship_pressure"
const VAR_STANCE := &"ship_stance"
const VAR_NAV_DESIRED_POINT := &"ship_nav_desired_point"
const VAR_NAV_HEADING_POINT := &"ship_nav_heading_point"
const VAR_NAV_SPEED_MULT := &"ship_nav_speed_mult"
const VAR_NAV_PERMIT_SPRINT := &"ship_nav_permit_sprint"
const VAR_NAV_MODE := &"ship_nav_mode"
const VAR_WEAPON_INTENT := &"ship_weapon_intent"
const VAR_SPECIAL_ATTACK_INTENT := &"ship_special_attack_intent"
const VAR_BOARDING_INTENT := &"ship_boarding_intent"
const VAR_SUPPORT_MODE := &"ship_support_mode"
const VAR_SUPPORT_TARGET := &"ship_support_target"
const VAR_SUPPORT_REASON := &"ship_support_reason"
# Legacy captured-ship blackboard variables. Support fleet AI uses the SUPPORT
# keys above; keep these names stable for the hidden capture flow and old trees.
const VAR_ALLY_MODE := &"ship_ally_mode"
const VAR_ALLY_TARGET := &"ship_ally_target"
const VAR_ALLY_REASON := &"ship_ally_reason"

const META_INTENT := "limbo_ai_intent"
const META_TARGET_ID := "limbo_ai_target_id"
const META_TARGET_DISTANCE := "limbo_ai_target_distance"
const META_PRESSURE_PHASE := "limbo_ai_pressure_phase"
const META_PRESSURE := "limbo_ai_pressure"
const META_STANCE := "limbo_ai_stance"
const META_NAV_TARGET_ID := "limbo_ai_nav_target_id"
const META_NAV_FRAME := "limbo_ai_nav_frame"
const META_NAV_DESIRED_POINT := "limbo_ai_nav_desired_point"
const META_NAV_HEADING_POINT := "limbo_ai_nav_heading_point"
const META_NAV_SPEED_MULT := "limbo_ai_nav_speed_mult"
const META_NAV_PERMIT_SPRINT := "limbo_ai_nav_permit_sprint"
const META_NAV_MODE := "limbo_ai_nav_mode"
const META_WEAPON_INTENT := "limbo_ai_weapon_intent"
const META_WEAPON_TARGET_ID := "limbo_ai_weapon_target_id"
const META_WEAPON_FRAME := "limbo_ai_weapon_frame"
const META_WEAPON_PRESSURE := "limbo_ai_weapon_pressure"
const META_SPECIAL_ATTACK_INTENT := "limbo_ai_special_attack_intent"
const META_SPECIAL_ATTACK_TARGET_ID := "limbo_ai_special_attack_target_id"
const META_SPECIAL_ATTACK_FRAME := "limbo_ai_special_attack_frame"
const META_SPECIAL_ATTACK_DISTANCE := "limbo_ai_special_attack_distance"
const META_BOARDING_INTENT := "limbo_ai_boarding_intent"
const META_BOARDING_TARGET_ID := "limbo_ai_boarding_target_id"
const META_BOARDING_FRAME := "limbo_ai_boarding_frame"
const META_BOARDING_DISTANCE := "limbo_ai_boarding_distance"
const META_BOARDING_ATTEMPT_DISTANCE := "limbo_ai_boarding_attempt_distance"
const META_SUPPORT_MODE := "limbo_ai_support_mode"
const META_SUPPORT_TARGET_ID := "limbo_ai_support_target_id"
const META_SUPPORT_FRAME := "limbo_ai_support_frame"
const META_SUPPORT_REASON := "limbo_ai_support_reason"
# Legacy captured-ship meta keys. Do not reuse for new support concepts.
const META_ALLY_MODE := "limbo_ai_ally_mode"
const META_ALLY_TARGET_ID := "limbo_ai_ally_target_id"
const META_ALLY_FRAME := "limbo_ai_ally_frame"
const META_ALLY_REASON := "limbo_ai_ally_reason"

const INTENT_ENGAGE := "engage"
const INTENT_CLOSE_DISTANCE := "close_distance"
const INTENT_HOLD := "hold"

const PHASE_STABLE := "stable"
const PHASE_DAMAGED := "damaged"
const PHASE_DESPERATE := "desperate"

const STANCE_BOMBARD := "bombard"
const STANCE_CLOSE_DISTANCE := "close_distance"
const STANCE_ORBIT_PRESSURE := "orbit_pressure"
const STANCE_WITHDRAW := "withdraw"
const STANCE_DESPERATE_PUSH := "desperate_push"

const WEAPON_HOLD_FIRE := "hold_fire"
const WEAPON_RANGED_PRESSURE := "ranged_pressure"
const WEAPON_BROADSIDE_READY := "broadside_ready"
const WEAPON_DESPERATE_VOLLEY := "desperate_volley"

const SPECIAL_HOLD := "special_hold"
const SPECIAL_CLOSE_DISTANCE := "special_close_distance"
const SPECIAL_FIRE_POT_READY := "fire_pot_ready"

const BOARDING_APPROACH := "boarding_approach"
const BOARDING_READY := "boarding_ready"

const SUPPORT_MODE_FOLLOW_FLAGSHIP := "follow_flagship"
const SUPPORT_MODE_RESCUE_FLAGSHIP := "rescue_flagship"
const SUPPORT_MODE_SCREEN_THREAT := "screen_threat"
const SUPPORT_MODE_BREACH_BOSS := "breach_boss"
const SUPPORT_MODE_REGROUP := "regroup"

# Legacy captured-ship modes paired with META_ALLY_*.
const ALLY_MODE_FOLLOW_FLAGSHIP := "follow_flagship"
const ALLY_MODE_GUARD_THREAT := "guard_threat"
const ALLY_MODE_REGROUP := "regroup"
